FROM ubuntu:18.04

WORKDIR /azp

COPY .token .
COPY Scripts/start.sh .

RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

RUN apt-get update \
    && apt-get install apt-utils -qq

RUN apt-get install -qq --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    curl \
    file \
    ftp \
    jq \
    git \
    gnupg \
    iproute2 \
    iputils-ping \
    locales \
    lsb-release \
    netcat \
    sudo \
    time \
    unzip \
    wget \
    zip \
&& rm -rf /var/lib/apt/lists/* && apt-get clean

# Install Docker
ENV DOCKER_VERSION 18.06.3-ce
RUN curl -fsSLO https://download.docker.com/linux/static/stable/x86_64/docker-$DOCKER_VERSION.tgz \
    && tar --strip-components=1 -xvzf docker-$DOCKER_VERSION.tgz -C /usr/local/bin && rm docker-$DOCKER_VERSION.tgz

# Install Kubectl
ENV KUBE_VERSION 1.14.8
RUN curl -fsSLO https://storage.googleapis.com/kubernetes-release/release/v$KUBE_VERSION/bin/linux/amd64/kubectl \
    && mv kubectl /usr/local/bin && chmod 755 /usr/local/bin/kubectl

# Install terrafor
ENV TERRAFORM_VERSION 0.12.20
RUN curl -fsSLO https://releases.hashicorp.com/terraform/$TERRAFORM_VERSION/terraform_${TERRAFORM_VERSION}_linux_amd64.zip \
    && unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /usr/local/bin \
    && chmod 755 /usr/local/bin/terraform && rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip

# Accept the TEE EULA
RUN mkdir -p "/root/.microsoft/Team Foundation/4.0/Configuration/TEE-Mementos" \
 && cd "/root/.microsoft/Team Foundation/4.0/Configuration/TEE-Mementos" \
 && echo '<ProductIdData><eula-14.0 value="true"/></ProductIdData>' > "com.microsoft.tfs.client.productid.xml"

# Install PowerShell Core
RUN wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update \
    && apt-get install -y powershell \
    && pwsh -Command "Install-Module -Name Az -Force" \
    && pwsh -Command "Install-Module -Name Pester -Force" \
    && pwsh -Command "Install-Module -Name Az.ResourceGraph -Force"

# Install Az cli
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash

RUN chmod +x start.sh

CMD ["./start.sh"]
